### ISSUE TITLE
Wish: document example use with bunyan

### ISSUE THREAD

**Issue by markstos** [myndzi/syslog2#5]
It appears that this is made to work with `bunyan`. An example showing how this is used as a `bunyan` stream would be helpful.

**Comment by markstos** [comment]
I tredi configuring bunyan like this:

```
{
  // Indicate that all logs come from the 'myapp' app
  name: 'myapp',
  // Log to STDOUT
//  stream: process.stdout,
  // Log at the "info" levels and above (excludes "debug" and "trace" output
  level: 'info',
  // Add serializers for 'err', 'req' and 'res' objects
  serializers: bunyan.stdSerializers,

  streams: [
  {
    level : 'info',
    type  : 'stream',
    stream: process.stdout,
  },
  {
    level: 'info',
    type: 'raw',
    stream : new Syslog({ name: 'myapp', connection: { type: 'unix' }})
  }]
}
```

but got this error message:

```
nodejs: ../src/stream_wrap.cc:339: static v8::Handle<v8::Value> node::StreamWrap::WriteStringImpl(const v8::Arguments&) [with node::encoding encoding = (node::encoding)1u]: Assertion `args.Holder()->InternalFieldCount() > 0' failed.
```

That's with Node.js 0.10.37.

**Comment by myndzi** [comment]
That's a weird error, and I'm not entirely sure what it means. I can tell that you are not connecting the stream though; try using `Syslog.create({ opts })` instead of `new Syslog({ opts })`

**Comment by myndzi** [comment]
I pushed an updated README.md to the git repo with an example of how to use with Bunyan. Please comment if you have more trouble, but I haven't heard back so I'm closing this for now.
