### ISSUE TITLE
Documentation for .connect() method missing

### ISSUE THREAD

**Issue by markstos** [myndzi/syslog2#6]
A method named `.connect()` is mentioned in the documentation but the `connect` method itself is not documented.

**Comment by myndzi** [comment]
It literally just runs a function when connected. Standard callback syntax: first arg is an error if an error occurred. It's the same thing as binding the 'connect' event.

I'll try to get to this and the other over the weekend.

**Comment by myndzi** [comment]
Pushed updated README.
